- src/test/kotlin/no/nav/k9/K9PunsjApplicationWithMocks.kt
Tilsvarende endring i frontend
https://github.com/navikt/k9-punsj-frontend/pull/121
> Endret mockserver til å kjøre på port 8085

- pom.xml
- src/main/kotlin/no/nav/k9/Innsending.kt
- src/main/kotlin/no/nav/k9/K9PunsjApplication.kt
- src/main/kotlin/no/nav/k9/Mappe.kt
- src/main/kotlin/no/nav/k9/OpenApi.kt
- src/main/kotlin/no/nav/k9/openapi/DurationMockConverter.kt
- src/main/kotlin/no/nav/k9/openapi/OpenApi.kt
- src/main/kotlin/no/nav/k9/pleiepengersyktbarn/soknad/PleiepengerSyktBarnRoutes.kt
- src/main/kotlin/no/nav/k9/pleiepengersyktbarn/soknad/PleiepengerSyktBarnSoknad.kt
- src/main/kotlin/no/nav/k9/pleiepengersyktbarn/soknad/PleiepengerSyktBarnSoknadValidator.kt
- src/main/resources/application.yml
- src/test/kotlin/no/nav/k9/K9PunsjApplicationTests.kt
- Periodisering
- Byttet til camelcase
- Lagt til tilsynsordning
- Rename: undermappe/personlig->personer, innhold->soeknad
> Periodisering av data, bytte til camelcase

- src/main/kotlin/no/nav/k9/Innsending.kt
- src/main/kotlin/no/nav/k9/mappe/Mappe.kt
- src/main/kotlin/no/nav/k9/mappe/MappeDtos.kt
- src/main/kotlin/no/nav/k9/openapi/OpenApi.kt
- src/main/kotlin/no/nav/k9/pleiepengersyktbarn/soknad/PleiepengerSyktBarnRoutes.kt
- src/main/kotlin/no/nav/k9/pleiepengersyktbarn/soknad/PleiepengerSyktBarnSoknadService.kt
Klassene "OasJournalpostInnhold" og "OasMappeInnholdSvar" erstattes av klasser i henholdsvis Innsending og MappeDtos.
> Forsøk på å fjerne dupliserte klasser i openapi

- src/main/kotlin/no/nav/k9/pleiepengersyktbarn/soknad/PleiepengerSyktBarnSoknadValidator.kt
- src/main/kotlin/no/nav/k9/pleiepengersyktbarn/soknad/PleiepengerSyktBarnSøknad.kt
Første gang jeg prøver meg på Kotlin. Si ifra hvis det er noe jeg har oversett/misforstått. :-)
> Fjerner 'signert' og 'perioder' og legger til 'periode' i søknad

- src/main/kotlin/no/nav/k9/pleiepengersyktbarn/soknad/PleiepengerSyktBarnSoknadConverter.kt
- src/test/kotlin/no/nav/k9/PleiepengersyktbarnTests.kt
- src/test/kotlin/no/nav/k9/pleiepengersyktbarn/soknad/PleiepengerSyktBarnSoknadConverterTests.kt
> Lagt til @Disabled på problematisk test og lagt til kommentarer på steder som må utbedres

- app/src/main/kotlin/no/nav/k9punsj/journalpost/JournalpostRoutes.kt
- app/src/main/kotlin/no/nav/k9punsj/journalpost/JournalpostService.kt
- app/src/main/kotlin/no/nav/k9punsj/journalpost/KopierJournalpost.kt
- app/src/main/kotlin/no/nav/k9punsj/journalpost/SafDtos.kt
- app/src/main/kotlin/no/nav/k9punsj/rest/eksternt/punsjbollen/PunsjbolleService.kt
- app/src/main/kotlin/no/nav/k9punsj/rest/eksternt/punsjbollen/PunsjbolleServiceImpl.kt
- app/src/main/kotlin/no/nav/k9punsj/rest/eksternt/punsjbollen/PunsjbolleServiceLokalt.kt
- app/src/test/kotlin/no/nav/k9punsj/TestContext.kt
- Unngår sjekk på at journalpost er knyttet til rett saksnummer - hvilket det aldri vil være på dette stadiet for til-personen.
> Sende med periode for å finne saksnummer på kopier-til-person

- app/src/main/kotlin/no/nav/k9punsj/journalpost/JournalpostRoutes.kt
- app/src/main/kotlin/no/nav/k9punsj/journalpost/KopierJournalpost.kt
- app/src/main/kotlin/no/nav/k9punsj/rest/eksternt/punsjbollen/PunsjbolleService.kt
- app/src/main/kotlin/no/nav/k9punsj/rest/eksternt/punsjbollen/PunsjbolleServiceImpl.kt
- app/src/main/kotlin/no/nav/k9punsj/rest/eksternt/punsjbollen/PunsjbolleServiceLokalt.kt
- app/src/main/kotlin/no/nav/k9punsj/rest/web/Innsending.kt
- app/src/main/kotlin/no/nav/k9punsj/rest/web/ruter/PleiepengerSyktBarnRoutes.kt
- app/src/test/kotlin/no/nav/k9punsj/PleiepengersyktbarnTests.kt
- app/src/test/kotlin/no/nav/k9punsj/TestContext.kt
- app/src/test/kotlin/no/nav/k9punsj/domenetjenester/MappeServiceTest.kt
- Bruker dette for å finne ut om en journalpost kan sendes til K9 eller ei
> Lagt til integrasjon mot nytt endepunkt i Punsjbollen 

- app/src/main/kotlin/no/nav/k9punsj/gosys/GosysRoutes.kt
- app/src/main/kotlin/no/nav/k9punsj/journalpost/JournalpostRoutes.kt
logger journalposter dette gjøres med.
> Setter ikke til ferdig når det lukkes/sendes til gosys

- app/src/main/kotlin/no/nav/k9punsj/domenetjenester/mappers/MapTilK9Format.kt
K9-sak ignorerer flaggene satt i infoFraPunsj
> psb-mapper - kringkaste flagg til journalposter

- app/pom.xml
- app/src/main/kotlin/no/nav/k9punsj/omsorgspenger/delingavomsorgsdager/DelingAvOmsorgsdagerConverter.kt
- app/src/main/kotlin/no/nav/k9punsj/omsorgspenger/overfoerdager/OverførDagerConverter.kt
- app/src/test/kotlin/no/nav/k9punsj/PleiepengersyktbarnTests.kt
- app/src/test/kotlin/no/nav/k9punsj/omsorgspenger/overfoerdager/OverførDagerApiTest.kt
- app/src/test/kotlin/no/nav/k9punsj/omsorgspenger/overfoerdager/OverførDagerConverterTest.kt
- app/src/test/kotlin/no/nav/k9punsj/rest/server/JournalpostInfoRoutesTest.kt
- pom.xml
Closes #292 
Closes #295
Closes #300
Closes #303
Closes #307
Closes #315
Closes #316 
Closes #317
Closes #321
> Dependency updates

- app/pom.xml
- app/src/main/kotlin/no/nav/k9punsj/domenetjenester/mappers/MapTilK9Format.kt
- app/src/main/kotlin/no/nav/k9punsj/domenetjenester/mappers/MapTilK9FormatV2.kt
- app/src/main/kotlin/no/nav/k9punsj/domenetjenester/mappers/PleiepengerSyktBarnMapper.kt
- app/src/main/kotlin/no/nav/k9punsj/rest/web/ruter/PleiepengerSyktBarnRoutes.kt
- app/src/test/kotlin/no/nav/k9punsj/util/PleiepengerSøknadVisningDtoUtils.kt
- Bruker fortsatt "gammel" mapping men sammenligner om vi ser noen forskjeller på feil/søknader.
- "Ny" mapping går rett fra visning-dto til k9-format, så man slipper unødvendig lag med mapping
> Ny mapping av søknader

- app/src/main/kotlin/no/nav/k9punsj/domenetjenester/mappers/MapTilK9FormatV2.kt
- app/src/test/kotlin/no/nav/k9punsj/domenetjenester/mappers/MapTilK9FormatV2Test.kt
- app/src/test/resources/psb/ferie-null-søknad.json
- app/src/test/resources/psb/uten-uttak-søknad.json
* Søtter å oppgi tid som timer:minutter
* Setter aldri fnr og fødselsdato på barn
* Blank virksomhetstype == null
* Blank regnskapsfører- navn/tlf == null
> Mindre mappingjusteringer

- app/src/main/kotlin/no/nav/k9punsj/rest/web/ruter/PleiepengerSyktBarnRoutes.kt
- app/src/test/kotlin/no/nav/k9punsj/PleiepengersyktbarnTests.kt
Så lenge det er minst en journalpost som kan sendes inn gjøres det
> Filtrer bort journalposter som ikke kan sendes inn.

- .github/workflows/build-master.yaml
- .github/workflows/build-pull-request.yaml
Vi er i ferd med å fase ut READ_PACKAGES_PAT, og ønsker derfor at dere bruker READER_TOKEN i stedet.
> Bytt til nytt PAT

- app/src/main/kotlin/no/nav/k9punsj/domenetjenester/MappeService.kt
- app/src/main/kotlin/no/nav/k9punsj/rest/web/ruter/PleiepengerLivetsSluttfaseRoutes.kt
Foresakte at pleietrengendeIdent ikke var satt i frontend før man refreshet siden og henta søknad på nytt.
> Fikser første innsending av pleiepenger i livets sluttfase.

- app/src/main/kotlin/no/nav/k9punsj/LoggFilter.kt
- app/src/main/kotlin/no/nav/k9punsj/dokarkiv/SafDtos.kt
- app/src/main/kotlin/no/nav/k9punsj/dokarkiv/SafGateway.kt
- app/src/main/kotlin/no/nav/k9punsj/domenetjenester/SoknadService.kt
- app/src/test/kotlin/no/nav/k9punsj/journalpost/SafDtosTest.kt
- mocks/src/main/kotlin/no/nav/k9punsj/wiremock/SafMocks.kt
Endret logfilter til o sette headers i response
> Sender ikke in journalposter med type Utgående

- app/src/main/kotlin/no/nav/k9punsj/akjonspunkter/AksjonspunktServiceImpl.kt
- app/src/main/kotlin/no/nav/k9punsj/brev/RestFormidlingService.kt
- app/src/main/kotlin/no/nav/k9punsj/brev/RestFormidlingServiceImpl.kt
- app/src/main/kotlin/no/nav/k9punsj/domenetjenester/MappeService.kt
- app/src/main/kotlin/no/nav/k9punsj/domenetjenester/SoknadService.kt
- app/src/main/kotlin/no/nav/k9punsj/journalpost/JournalpostService.kt
- app/src/main/kotlin/no/nav/k9punsj/kafka/KafkaConfig.kt
- app/src/main/kotlin/no/nav/k9punsj/korrigeringinntektsmelding/KorrigeringInntektsmeldingService.kt
- app/src/main/kotlin/no/nav/k9punsj/omsorgspengeraleneomsorg/OmsorgspengerAleneOmsorgService.kt
- app/src/main/kotlin/no/nav/k9punsj/omsorgspengerkronisksyktbarn/OmsorgspengerKroniskSyktBarnService.kt
- app/src/main/kotlin/no/nav/k9punsj/omsorgspengermidlertidigalene/OmsorgspengerMidlertidigAleneService.kt
- app/src/main/kotlin/no/nav/k9punsj/omsorgspengerutbetaling/OmsorgspengerutbetalingService.kt
- app/src/main/kotlin/no/nav/k9punsj/pleiepengerlivetssluttfase/PleiepengerLivetsSluttfaseService.kt
- app/src/main/kotlin/no/nav/k9punsj/pleiepengersyktbarn/PleiepengerSyktBarnService.kt
> Revert "Flyttet aksjonspunkthåndtering ur søknadsservice-klassen."

- app/src/main/kotlin/no/nav/k9punsj/journalpost/JournalpostRoutes.kt
Sender ikke-støttet-journalpost om en journalpost ikke skall till k9sak eller infotrygd
> Sender ikke-støttet-journalpost

- pom.xml
Dette inkluderer blant annet validering av at mottattdato ikke kan være i fremtiden.
Endringer i k9-format siden forrige versjon k9-punsj benyttet:
https://github.com/navikt/k9-format/compare/5.8.8...6.0.2
> Oppdaterer versjonen til k9-format.

- README.md
- app/src/main/kotlin/no/nav/k9punsj/felles/dto/FellesDtoer.kt
- app/src/main/kotlin/no/nav/k9punsj/journalpost/JournalpostRoutes.kt
- app/src/main/kotlin/no/nav/k9punsj/journalpost/KopierJournalpostRoute.kt
- app/src/main/kotlin/no/nav/k9punsj/journalpost/PunsjJournalpost.kt
Refaktorert utledeFagsakYtelseType-funktion & tilgangssjekk i kopierjournalpost
Lagt på kommentar om deploy-strategi i readme
> Refaktoreringer & deploy-strategi i readme

- app/src/main/kotlin/no/nav/k9punsj/kafka/KafkaHendelseProducer.kt
- nais/dev-fss.yml
- nais/prod-fss.yml
> Revert "Dokumenthendelse-topic på Aiven"

- app/src/main/kotlin/no/nav/k9punsj/akjonspunkter/AksjonspunktServiceImpl.kt
- app/src/main/kotlin/no/nav/k9punsj/brev/BrevServiceImpl.kt
- app/src/main/kotlin/no/nav/k9punsj/fordel/AivenConsumer.kt
- app/src/main/kotlin/no/nav/k9punsj/innsending/KafkaInnsendingClient.kt
- app/src/main/kotlin/no/nav/k9punsj/jobber/SjekkOmUtløptJobb.kt
- app/src/main/resources/application.yml
- app/src/test/kotlin/no/nav/k9punsj/MockConfiguration.kt
- app/src/test/kotlin/no/nav/k9punsj/akjonspunkter/AksjonspunktServiceImplTest.kt
- app/src/test/kotlin/no/nav/k9punsj/brev/BrevServiceImplTest.kt
- app/src/test/kotlin/no/nav/k9punsj/jobber/SjekkOmUtløptJobbTest.kt
- nais/dev-fss.yml
- nais/prod-fss.yml
Los er ikke idempotent, bytter strategi til att los kjør consumer på både on-prem + aiven och punsj går direkt fra on-prem -> aiven.
> Dubbla konsumers for fordel-topic (onprem+aiven)

- app/src/main/kotlin/no/nav/k9punsj/domenetjenester/MappeService.kt
- app/src/main/kotlin/no/nav/k9punsj/felles/FagsakYtelseType.kt
- app/src/main/kotlin/no/nav/k9punsj/opplaeringspenger/MapOlpTilK9Format.kt
- app/src/main/kotlin/no/nav/k9punsj/opplaeringspenger/OpplaeringspengerRoutes.kt
- app/src/main/kotlin/no/nav/k9punsj/opplaeringspenger/OpplaeringspengerService.kt
- app/src/main/kotlin/no/nav/k9punsj/opplaeringspenger/OpplaeringspengerSoknadDto.kt
- app/src/main/kotlin/no/nav/k9punsj/opplaeringspenger/OpplaeringspengerSoknadOpenApi.kt
WIP, ska fikse format på DTO før denne merges in.
> Støtte for opplæringspenger

- app/src/main/kotlin/no/nav/k9punsj/integrasjoner/k9sak/K9SakServiceImpl.kt
- app/src/main/kotlin/no/nav/k9punsj/kafka/KafkaHendelseProducer.kt
K9-sak støtter ikke client credentials, dropper azure token tils det er implementert
> K9-sak tilbake på STS, forbedret logging i HendelseProducer

- app/src/main/kotlin/no/nav/k9punsj/integrasjoner/arbeidsgivere/AaregClient.kt
- app/src/test/kotlin/no/nav/k9punsj/MockConfiguration.kt
- app/src/test/kotlin/no/nav/k9punsj/integrasjoner/arbeidsgivere/AaregClientTest.kt
- mocks/src/main/kotlin/no/nav/k9punsj/wiremock/AaregMocks.kt
- nais/dev-fss.yml
- nais/prod-fss.yml
Samt, bytter til Azure klient for henting av token mot aareg.
Lukker #765.
> Migrerer til ny tjeneste for aareg-services (API v2)

- app/src/main/kotlin/no/nav/k9punsj/felles/dto/SaksnummerDto.kt
- app/src/main/kotlin/no/nav/k9punsj/integrasjoner/k9sak/K9SakService.kt
- app/src/main/kotlin/no/nav/k9punsj/integrasjoner/k9sak/K9SakServiceImpl.kt
- app/src/main/kotlin/no/nav/k9punsj/integrasjoner/punsjbollen/PunsjbolleService.kt
- app/src/main/kotlin/no/nav/k9punsj/integrasjoner/punsjbollen/RestPunsjbolleService.kt
- app/src/test/kotlin/no/nav/k9punsj/rest/eksternt/k9sak/LokalK9SakService.kt
- app/src/test/kotlin/no/nav/k9punsj/rest/eksternt/k9sak/TestK9SakService.kt
- app/src/test/kotlin/no/nav/k9punsj/rest/eksternt/punsjbollen/LokalPunsjbolleService.kt
- app/src/test/kotlin/no/nav/k9punsj/rest/eksternt/punsjbollen/TestPunsjbolleService.kt
Fjernet ubrukt opprettEllerHentFagsaksnummer-metod 
Lagt til støtte for o hente siste k9sak saksnummer for en periode
> Migrerer punsjbolle-funktioner in i punsj

- app/src/main/kotlin/no/nav/k9punsj/CoroutineRequestContext.kt
- app/src/main/kotlin/no/nav/k9punsj/felles/Feil.kt
- app/src/main/kotlin/no/nav/k9punsj/felles/Typer.kt
- app/src/main/kotlin/no/nav/k9punsj/journalpost/JournalpostInfoOpenApi.kt
- app/src/main/kotlin/no/nav/k9punsj/journalpost/JournalpostInfoRoutes.kt
- app/src/main/kotlin/no/nav/k9punsj/journalpost/JournalpostOpenApi.kt
- app/src/main/kotlin/no/nav/k9punsj/journalpost/JournalpostRoutes.kt
- app/src/main/kotlin/no/nav/k9punsj/journalpost/dto/JournalpostIderDto.kt
- app/src/main/kotlin/no/nav/k9punsj/journalpost/dto/JournalpostMottaksHaandteringDto.kt
- app/src/main/kotlin/no/nav/k9punsj/journalpost/dto/LukkJournalpostDto.kt
- app/src/main/kotlin/no/nav/k9punsj/journalpost/dto/ResultatDto.kt
- app/src/main/kotlin/no/nav/k9punsj/journalpost/dto/RutingDto.kt
- app/src/main/kotlin/no/nav/k9punsj/journalpost/dto/SettPåVentDto.kt
- app/src/main/kotlin/no/nav/k9punsj/journalpost/dto/SkalTilInfotrygdSvar.kt
- app/src/main/kotlin/no/nav/k9punsj/journalpost/dto/SøkUferdigJournalposter.kt
- app/src/main/kotlin/no/nav/k9punsj/korrigeringinntektsmelding/KorrigeringInntektsmeldingRoutes.kt
- app/src/main/kotlin/no/nav/k9punsj/korrigeringinntektsmelding/KorrigeringInntektsmeldingService.kt
- app/src/main/kotlin/no/nav/k9punsj/notat/NotatPDFGenerator.kt
- app/src/main/kotlin/no/nav/k9punsj/notat/PDFGenerator.kt
- app/src/main/kotlin/no/nav/k9punsj/notat/PdfaValidator.kt
- app/src/main/kotlin/no/nav/k9punsj/omsorgspengerutbetaling/OmsorgspengerutbetalingService.kt
- app/src/test/kotlin/no/nav/k9punsj/rest/server/PunsjJournalpostInfoRoutesTest.kt
Flyttet DTOer som ikke var felles.
PDF-klasser fra Utils til Notat-package.
> Refaktorert OMP_UT til o bli like de andre ytelserne

- app/src/main/kotlin/no/nav/k9punsj/brev/MapDokumentTilK9Formidling.kt
- app/src/main/kotlin/no/nav/k9punsj/journalpost/JournalpostRoutes.kt
- app/src/main/kotlin/no/nav/k9punsj/journalpost/JournalpostService.kt
- app/src/main/kotlin/no/nav/k9punsj/korrigeringinntektsmelding/MapOmsTilK9Format.kt
- app/src/main/kotlin/no/nav/k9punsj/omsorgspengeraleneomsorg/MapOmsAOTilK9Format.kt
- app/src/main/kotlin/no/nav/k9punsj/omsorgspengerkronisksyktbarn/MapOmsKSBTilK9Format.kt
- app/src/main/kotlin/no/nav/k9punsj/omsorgspengermidlertidigalene/MapOmsMATilK9Format.kt
- app/src/main/kotlin/no/nav/k9punsj/omsorgspengerutbetaling/MapOmsUtTilK9Format.kt
- app/src/main/kotlin/no/nav/k9punsj/opplaeringspenger/MapOlpTilK9Format.kt
- app/src/main/kotlin/no/nav/k9punsj/pleiepengerlivetssluttfase/MapPlsfTilK9Format.kt
- app/src/main/kotlin/no/nav/k9punsj/pleiepengersyktbarn/MapPsbTilK9Format.kt
- pom.xml
- Logger mapping-feil på warn-level. Refaktoreret henting av punsjinnsendingtype for å spare ett DB kall
- Snakeyaml 2.0
> Logger mappingfeil på warn-lvl, refaktorering, snakeyaml 2.0

- app/src/main/kotlin/no/nav/k9punsj/CoroutineRequestContext.kt
> Logger Throwable på warn-nivå.

- pom.xml
- src/main/kotlin/no/nav/k9punsj/brev/BrevRoutes.kt
- src/main/kotlin/no/nav/k9punsj/integrasjoner/arbeidsgivere/ArbeidsgiverRoutes.kt
- src/main/kotlin/no/nav/k9punsj/journalpost/JournalpostRoutes.kt
- src/main/kotlin/no/nav/k9punsj/korrigeringinntektsmelding/KorrigeringInntektsmeldingRoutes.kt
- src/main/kotlin/no/nav/k9punsj/omsorgspengeraleneomsorg/OmsorgspengerAleneOmsorgRoutes.kt
- src/main/kotlin/no/nav/k9punsj/omsorgspengeraleneomsorg/OmsorgspengerAleneOmsorgService.kt
- src/main/kotlin/no/nav/k9punsj/omsorgspengerkronisksyktbarn/OmsorgspengerKroniskSyktBarnRoutes.kt
- src/main/kotlin/no/nav/k9punsj/omsorgspengermidlertidigalene/OmsorgspengerMidlertidigAleneRoutes.kt
- src/main/kotlin/no/nav/k9punsj/omsorgspengerutbetaling/OmsorgspengerutbetalingRoutes.kt
- src/main/kotlin/no/nav/k9punsj/opplaeringspenger/OpplaeringspengerRoutes.kt
- src/main/kotlin/no/nav/k9punsj/person/PersonRoutes.kt
- src/main/kotlin/no/nav/k9punsj/pleiepengerlivetssluttfase/PleiepengerLivetsSluttfaseRoutes.kt
- src/main/kotlin/no/nav/k9punsj/pleiepengersyktbarn/PleiepengerSyktBarnRoutes.kt
- src/main/kotlin/no/nav/k9punsj/sak/SakerRoutes.kt
- src/main/kotlin/no/nav/k9punsj/tilgangskontroll/InnloggetUtils.kt
- src/main/kotlin/no/nav/k9punsj/tilgangskontroll/abac/IPepClient.kt
- src/main/kotlin/no/nav/k9punsj/tilgangskontroll/abac/PepClient.kt
- src/main/kotlin/no/nav/k9punsj/tilgangskontroll/abac/XacmlRequestBuilder.kt
- src/test/kotlin/no/nav/k9punsj/abac/AlltidTilgangPepClient.kt
> Revert "Abac-kall går via inloggetUtils, ryddet opp i pepclient, erstattet gson med jackson"

- nais/dev-fss.yml
- nais/prod-fss.yml
- src/main/kotlin/no/nav/k9punsj/CoroutineRequestContext.kt
- src/main/kotlin/no/nav/k9punsj/integrasjoner/k9sak/K9SakServiceImpl.kt
- src/main/kotlin/no/nav/k9punsj/journalpost/JournalpostInfoRoutes.kt
- src/main/kotlin/no/nav/k9punsj/tilgangskontroll/AccessTokenClients.kt
- src/main/kotlin/no/nav/k9punsj/tilgangskontroll/oidc/OidcRoutes.kt
- src/main/resources/application.yml
- src/test/kotlin/no/nav/k9punsj/rest/server/PunsjJournalpostInfoRoutesTest.kt
- src/test/kotlin/no/nav/k9punsj/wiremock/AccessTokenMocks.kt
> Revert "Bruker azure-token for k9kall, ryddet vekk referenser til STS"

- nais/dev-fss.yml
- nais/prod-fss.yml
- src/main/kotlin/no/nav/k9punsj/CoroutineRequestContext.kt
- src/main/kotlin/no/nav/k9punsj/integrasjoner/k9sak/K9SakServiceImpl.kt
- src/main/kotlin/no/nav/k9punsj/journalpost/JournalpostInfoRoutes.kt
- src/main/kotlin/no/nav/k9punsj/tilgangskontroll/AccessTokenClients.kt
- src/main/kotlin/no/nav/k9punsj/tilgangskontroll/oidc/OidcRoutes.kt
- src/main/resources/application.yml
- src/test/kotlin/no/nav/k9punsj/rest/server/PunsjJournalpostInfoRoutesTest.kt
- src/test/kotlin/no/nav/k9punsj/wiremock/AccessTokenMocks.kt
Reverts navikt/k9-punsj#1076
Venter på att k9-sak kaller punsj med AD tokens.
> Revert "Revert "Bruker azure-token for k9kall, ryddet vekk referenser til STS""

- pom.xml
> Revert "Bump no.nav.k9.sak:kontrakt from 4.1.4 to 4.1.9"

- src/main/kotlin/no/nav/k9punsj/integrasjoner/pdl/PdlServiceImpl.kt
- src/main/kotlin/no/nav/k9punsj/person/Behandling.kt
PDL vil bruke dokumenterte opplysninger i behandlingskatalogen for tilgangskontroll av opplysninger spør om.
> Legger på behandlingsnummer header på kall til PDL.

- src/main/kotlin/no/nav/k9punsj/akjonspunkter/AksjonspunktServiceImpl.kt
- src/main/kotlin/no/nav/k9punsj/integrasjoner/k9losapi/K9LosOppgaveDto.kt
- src/main/kotlin/no/nav/k9punsj/journalpost/dto/PunsjJournalpost.kt
- src/main/kotlin/no/nav/k9punsj/journalpost/postmottak/PostMottakService.kt
- src/test/kotlin/no/nav/k9punsj/AbstractContainerBaseTest.kt
- src/test/kotlin/no/nav/k9punsj/journalpost/postmottak/PostMottakServiceTest.kt
- src/test/kotlin/no/nav/k9punsj/util/KafkaUtils.kt
- src/test/resources/application-test.yaml
Sendes dermed med i event til LOS
> Setter på journalførtTidspunkt etter journalføring

- .github/workflows/build-master-deploy-dev.yaml
> Revert "Replaced reader_token with octo-sts token"

- src/main/kotlin/no/nav/k9punsj/fordel/HendelseMottaker.kt
- src/main/kotlin/no/nav/k9punsj/integrasjoner/dokarkiv/SafDtos.kt
> Revert "Setter journalførtTidspunkt for journalpostkopier som er ferdigstilt."

- README.md
- nais/dev-fss.yml
- nais/prod-fss.yml
- [SAF](https://github.com/navikt/saf/blob/master/nais/q2-config.json#L57-L65)
- [Dokarkiv](https://github.com/navikt/dokarkiv/blob/master/nais/q2-config.json#L297-L301)
- [Oppgave](https://github.com/navikt/oppgave/blob/master/nais/app-q2.yaml#L291-L293)
- [AAREG-services](https://github.com/navikt/aareg-services/blob/main/.nais/dev-fss/q2.yaml#L552-L558)
> Q2 migrering

- .github/workflows/build-master-deploy-dev-gcp.yaml
- nais/dev-gcp.yml
Forsøke deploy til dev-gcp. 
I første omgang ønsker jeg å deploye for å opprette en databaseinstans i GCP for å prøve å migrere data fra dev-fss til dev-gcp via pg_dump
> Forsøke deploy til dev-gcp
